#ifndef CONSTANTS_H
#define CONSTANTS_H

#define MIN_EPSILON 1e-12
#define MAX_EPSILON 1e-1
#define MAX_EQUATION_NUMBER 10
#define MIN_EQUATION_NUMBER 2
#define MAX_COEFFICIENT 1000
#define MIN_COEFFICIENT -1000
#define MAX_RESULT_VECTOR 1000000
#define MIN_RESULT_VECTOR -1000000
#define ESCAPE_ASCII_CODE 27

#endif // CONSTANTS_H
